# Generated by Django 4.1.5 on 2023-04-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropName', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=25)),
                ('temp', models.FloatField()),
                ('pH', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('water_needed', models.FloatField()),
            ],
        ),
    ]
