# Generated by Django 4.1.5 on 2023-04-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_farm', models.CharField(default='farm', max_length=255)),
                ('template_name', models.CharField(default='Farm Inc.', max_length=255)),
                ('farm_location', models.CharField(default='Farm Location', max_length=255)),
                ('farm_contacts', models.CharField(default='02 xxx-xxxx / 02 xxx-xxxx', max_length=255)),
            ],
        ),
    ]
