# Generated by Django 4.1.5 on 2023-04-05 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField()),
                ('action_date', models.DateField()),
                ('action_time', models.TimeField()),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_user', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_farm_name', to='home.farm')),
            ],
        ),
    ]
